### ISSUE TITLE
Median Absolute Deviation for sparse numerical data

### ISSUE THREAD

**Issue by rmazzine** [microsoft/DiCE#15]
https://github.com/microsoft/DiCE/blob/072f6f7ac62ba6129e6f8ac4d67fbbe1d7359863/dice_ml/data_interfaces/public_data_interface.py#L192

When the input data has continuous values with sparse input (majority 0), the calculated MAD will be zero. Then, this will cause a problem on:

https://github.com/microsoft/DiCE/blob/072f6f7ac62ba6129e6f8ac4d67fbbe1d7359863/dice_ml/dice_interfaces/dice_tensorflow1.py#L273

**Comment by rmazzine** [comment]
One possible solution might be using a "hard coded" value when the feature MAD is zero. This value could have a very high value to ensure the weight is large.

**Comment by raam93** [comment]
In the latest version, this won't happen as `data_interface.get_valid_mads()` method takes care of such cases. Currently, we don't add a normalization constant for such features and so they are considered to be of the same weight as other categorical and unweighted continuous features. We do this because, as far as we can see, there is no consensus on the normalization factor. Your solution is definitely one way to tackle the problem. However, instead of hardcoding, we give control to users who can feed their values directly through "feature_weights" parameter.

**Comment by rmazzine** [comment]
Indeed I used an older version, my bad!

Definitely there is no consensus on how to deal with this kind of normalization. However, the current code replaces MAD to 1 and, then, we would have a weight of 1 for those features. While other variables, that have higher variation, will get weights with orders of magnitude higher.

This can generate a side-effect of those variables (that are sparse and have very low variation) be preferred when changing their values. While, as their MAD is zero they actually should have "infinite" weight.

But, again, there is no best way to solve that indeed! But this can (negatively) affect your clever way to weight variables!
